### PR TITLE
Introduce treeTypes config param

### PR DESCRIPTION
**Pull request by canufeel**
During Ember app concatenation without treeTypes param set to `all` the plugin would first concatenate all assets separately (Templates, js, css, other assets) which is a result of running [toTree](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1657) and then try to concatenate them again, after they are merged together. Such behaviour would fail even for default ember app blueprint created by `ember new` command as the separate assets do not have the input files required by the plugin import and so the build would usually fail while trying to concat templates.

With default option set for `treeTypes` the plugin would keep its original behaviour. However `treeTypes` allow to apply the plugin only to the specified list of tree types. Setting the `treeTypes` to `['all']` would result in plugin applied only to the resulting merged tree which is actually the expected behaviour if we just want to concat `.js` and `.css` assets which are already concatenated by Ember.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@canufeel I know I was getting errors after updating some of the stuff in this addon. Are you able to successfully use the addon, in its current state or does this PR fix some things? What version of Ember are you on?

**Comment by canufeel** [comment]
@rwwagner90 Hi! Yes the addon works just fine if you set the `treeTypes: ['all']` in the config. Our ember version is 2.4.x.

Setting `treeTypes` to `['all']` would apply the addon only to the trees of type `all` which is the result of `mergeTrees` on templates, css, js, other assets and anything else that you might have. Without it Ember build pipeline would run `postprocessTree` hook first for templates, css, js and other assets and then would run it again for the merged tree. The build fails because for templates you won't have any vendor.js/.css or app.js/.css in the `input` folder which plugin expects so you don't really want to run the `ember-cli-concat` `postprocessTree` hook for them.

**Comment by rwwagner90** [comment]
@canufeel just to be clear, does this addon not work without these changes for you or is this just an enhancement?

**Comment by canufeel** [comment]
@rwwagner90 Its both. It doesn't work without it, even if we try to introduce this addon to the blank ember application which is just created by `ember new` command + an enhancement for those who made it work some other way. I made sure that with default settings the way plugin works wouldn't be altered as otherwise for someone upgrading might mean breaking their builds.

**Comment by rwwagner90** [comment]
@canufeel I went ahead and merged the changes and released a new version. Do you think we should make the default `'all'` since it does not work without specifying it? We could then document that you can override it if you want.

**Comment by canufeel** [comment]
@rwwagner90 Thanks for the merge. I would add the docs tomorrow. I think that if we are going to make it a default we'd better state that either in the `readme.md` or add `changelog.md` to describe the changes that happen across versions. If you are ok with that i can make another PR with `changelog.md` in it.

**Comment by rwwagner90** [comment]
@canufeel I am okay with that. I don't think the old way of doing things works with any modern Ember versions anyway. 

I went ahead and made `'all'` the default, and I attempted to use it for my website, but the JS seems to break after the concat. The site all runs fine, but styles are all messed up. I set `concat: false` for the JS and it works just concatenating the CSS, so the issue is not there, something with the JS order of concatenation must break things somehow.

Any ideas on that @canufeel?

**Comment by canufeel** [comment]
@rwwagner90 Not really. Hope you would be able to resolve this.

**Comment by rwwagner90** [comment]
@canufeel it was because of ember-component-css. I resolved the issue

**Pull request merged**
