### PR TITLE
Add support for pre-loading css

### PR DESCRIPTION
**Pull request by jeroenbell**
When enabled, this adds `<link rel="preload" href="/path/to/css" as="style">` ([browser support](https://caniuse.com/link-rel-preload)) for preloading css

### CODE REVIEW

**Comment by jeroenbell** [comment]
@sir-dunxalot I have another proposal 🙂

**Comment by sir-dunxalot** [comment]
@jeroenbell Thank you! Will aim to release this with your other PR shortly, assuming no issues or comments.

**Comment by sir-dunxalot** [comment]
@jeroenbell Looks like this changes conflicts with a change in your other PR, #72, which is merged. Once fixed, I'll merge this PR into master too.

**Comment by jeroenbell** [comment]
@sir-dunxalot Thank you! I've addressed the merge conflict and made a small change.

**Comment by sir-dunxalot** [comment]
Released in [2.3.0](https://github.com/sir-dunxalot/ember-cli-concat/releases/tag/2.3.0).

**Pull request merged**
